"""new vocab favorite relationship

Revision ID: c5ac56ca99a9
Revises: 3ad9d7e347da
Create Date: 2023-04-19 10:15:12.487410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5ac56ca99a9'
down_revision = '3ad9d7e347da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vocab_words', schema=None) as batch_op:
        batch_op.add_column(sa.Column('module_content_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_vocab_words_module_content_id_module_contents'), 'module_contents', ['module_content_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vocab_words', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_vocab_words_module_content_id_module_contents'), type_='foreignkey')
        batch_op.drop_column('module_content_id')

    # ### end Alembic commands ###
